swagger: "2.0"
info:
  version: "1.0.0"
  title: "E-Auction API"
  description: "E-Auction Application is microservice based Cloud Native Application. The Main purpose of E-Auction is to provide the ability to initiate sale, purchase and bid for a product by the customer. The core modules of E-Auction app are: Put a new product on auction with starting bid price.Bid for the product. Update the bid price. Enlisting of bids placed on any product."
  contact:
    name: "Dante Arceneaux"
    email: "dantearcene@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/e-auction/api/v1/"
schemes: 
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /products:
    get:
      summary: "Get all products"
      description: "Returns all products from the system that the user has access to"
      responses:
        200:
          description: "returns success."
          schema:
            type: "application/json"
            example: 
              - id: 1
                buyer: "2345234235463256"
                product: "9845943859834598"
                firstName: "Dante"
                lastName: "Arceneaux"
                email: "dante@gmail.com"
                bidAMount: 100
                createdAt: "2020-01-01 00:00:00"
                __v: 0  
        400:
          description: "returns bad request."
        500:
          description: "returns internal server error."
  /users:
    get:
      summary: "Get all users"
      description: "Returns all users"
      responses:
        200:
          description: "returns success."
          schema:
            type: "application/json"
            example: 
              - id: 1
                role: "buyer"
                firstName: "Dante"
                lastName: "Arceneaux"
                city: "New Orleans"
                state: "LA"
                phone: "5045555555"
                email: "dante@gmail.com"
                bidAMount: 100
                createdAt: "2020-01-01 00:00:00"
                __v: 0  

  /bids:
    get:
      summary: "Get all bids"
      description: "Returns all bids"
      responses:
        200:
          description: "returns success."
          schema:
            type: "application/json"
            example: 
              - id: 1
                buyer: "2345234235463256"
                product: "9845943859834598"
                firstName: "Dante"
                lastName: "Arceneaux"
                city: "New Orleans"
                state: "LA"
                phone: "5045555555"
                email: "dante@gmail.com"
                bidAMount: 100
                createdAt: "2020-01-01 00:00:00"
                __v: 0
            
            
            

  



      
        

     

   

